# Copyright (c) 2025 devgagan : https://github.com/devgaganin.  
# Licensed under the GNU General Public License v3.0.  
# See LICENSE file in the repository root for full license text.

import os
from dotenv import load_dotenv

load_dotenv()

# VPS --- FILL COOKIES 🍪 in """ ... """ 

INST_COOKIES = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.instagram.com	TRUE	/	TRUE	1783611437	ps_n	1
#HttpOnly_.instagram.com	TRUE	/	TRUE	1758220458	datr	Avm8Zmw64JpuiAWjRTrfNN1c
.instagram.com	TRUE	/	TRUE	1763656392	ds_user_id	75963150222
.instagram.com	TRUE	/	TRUE	1790440392	csrftoken	p0Mc5VGPl58rPBDrgj0mEi9f8n7i5VQz
#HttpOnly_.instagram.com	TRUE	/	TRUE	1787416375	ig_did	F2FB8DD2-CB5B-44D7-9D6D-30DBF437F59B
#HttpOnly_.instagram.com	TRUE	/	TRUE	1783611437	ps_l	1
.instagram.com	TRUE	/	TRUE	1756485187	wd	1920x911
.instagram.com	TRUE	/	TRUE	1758220457	mid	Zrz5AgALAAE2OCsrAXl_jTwDN4qo
#HttpOnly_.instagram.com	TRUE	/	TRUE	1787416377	sessionid	75963150222%3ArgGjiY2nrcEP7N%3A3%3AAYcXoW9SuVV0TGxP0Rrk9e3IvY2OOkr4gkjeIkU0tg
#HttpOnly_.instagram.com	TRUE	/	TRUE	1755966793	rur	"EAG\05475963150222\0541787416422:01fecb0d8ebdc15265fefb3f84b65ac4b1c6f6a24338ab0d514c6b8d46bdb7c4b36750c6"
"""

YTUB_COOKIES = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1771432332	VISITOR_PRIVACY_METADATA	CgJJThIEGgAgVQ%3D%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1789237092	__Secure-3PSID	g.a000zwg9s62VPTPRmvITW0ArZhJZtrJVfSzZGY0dI3BDuCp_CetUyUQSETmU14eNvQUaXGF3awACgYKAZ0SARYSFQHGX2MiUCSnQcmxPb3Nz3rHVk2x3BoVAUF8yKqGoF6VaLhL7UMb9zn86A0l0076
.youtube.com	TRUE	/	FALSE	1787416332	SIDCC	AKEyXzVTN8wc-oOS5BiwHhs-qthxTNDSwS1AS41EeIrSaPJc6QPSIfhSdpwcPT-R6bPs-eeFAUE
.youtube.com	TRUE	/	FALSE	1788704708	SID	g.a000zwg9s62VPTPRmvITW0ArZhJZtrJVfSzZGY0dI3BDuCp_CetUnmjU1ipKmxN0PAjZNbbw_QACgYKASsSARYSFQHGX2Miz7WQTKF-apVefjDnX0utTBoVAUF8yKpOlwMDXcZvS94rbkWiSQF60076
#HttpOnly_.youtube.com	TRUE	/	TRUE	1787416328	__Secure-1PSIDTS	sidts-CjQB5H03P41Zehj4SikWQr21z40ubTWndIoQGuGWHnoI5zV6jG4KQT2IJkqxyP4EXtbPfPEhEAA
.youtube.com	TRUE	/	TRUE	1788704708	SAPISID	hfsC4zFCrxmPdTwb/AuvyOFKlKIcF6LAVg
#HttpOnly_.youtube.com	TRUE	/	TRUE	1787416332	__Secure-1PSIDCC	AKEyXzXecBoNK9CYwHXnRXyAJHB9xAvrsVG45ouRPT0YAmZgZRbOiDMGSX_rA2UuoGNgNy2aHw
#HttpOnly_.youtube.com	TRUE	/	TRUE	1788704708	SSID	AIdbHSTMF99Tt76uH
.youtube.com	TRUE	/	TRUE	1788704708	__Secure-1PAPISID	hfsC4zFCrxmPdTwb/AuvyOFKlKIcF6LAVg
#HttpOnly_.youtube.com	TRUE	/	TRUE	1788704708	__Secure-1PSID	g.a000zwg9s62VPTPRmvITW0ArZhJZtrJVfSzZGY0dI3BDuCp_CetUY3593jBQBrgpr-P-XK8bUAACgYKAcESARYSFQHGX2Mi_xL9xokXJPOASPIzd05IRxoVAUF8yKqiWnDdrM5ot0s8BDzomq_-0076
.youtube.com	TRUE	/	TRUE	1789237092	__Secure-3PAPISID	hfsC4zFCrxmPdTwb/AuvyOFKlKIcF6LAVg
#HttpOnly_.youtube.com	TRUE	/	TRUE	1787416332	__Secure-3PSIDCC	AKEyXzXj0XARjAN9jIIZ78HOcNztEQBpskBlEQ0aX-FyTnubIUCYXrcK43IXNprWF5-xR6rcbQ
#HttpOnly_.youtube.com	TRUE	/	TRUE	1787416328	__Secure-3PSIDTS	sidts-CjQB5H03P41Zehj4SikWQr21z40ubTWndIoQGuGWHnoI5zV6jG4KQT2IJkqxyP4EXtbPfPEhEAA
.youtube.com	TRUE	/	FALSE	1788704708	APISID	cPs_vZ3tqEnt1YGi/ALHztvxwbE6wbSecb
#HttpOnly_.youtube.com	TRUE	/	FALSE	1788704708	HSID	AJRjqguhRgRjKejZK
#HttpOnly_.youtube.com	TRUE	/	TRUE	1787852026	LOGIN_INFO	AFmmF2swRQIgRWNNWrDLkOTV14AvaxUy5AZEFRR4SfZ4aN3Dz2CvSEECIQC14MO7FRhNJdZu1Z0bFcDffM8CX3IIhKHANUAhuvfK5Q:QUQ3MjNmd0NPcTFKdDZGSU5BaUJrRzJxTFFzZUZMREFOUklzLTJka2Q4TDhEOWdFUzVzVHd5dWtSZlFKT1J5SHZpXzd4RG9WaG0tWkxjWi16ZVNHQnlTTDdqLThwcF9vbXltUjllcHpDbktHU2RwbW9XWHFybGU4VTFTel9TM20ycXZTbHA5TFFiS0xEQnRMY05jeVJXXzVYOXlhZkg4emVn
.youtube.com	TRUE	/	TRUE	1790440324	PREF	f6=40000000&tz=Asia.Calcutta&f7=100
#HttpOnly_.youtube.com	TRUE	/	TRUE	1771432332	VISITOR_INFO1_LIVE	B967f8vEzYs
"""

API_ID = os.getenv("API_ID", "")
API_HASH = os.getenv("API_HASH", "")
BOT_TOKEN = os.getenv("BOT_TOKEN", "")
MONGO_DB = os.getenv("MONGO_DB", "")
OWNER_ID = list(map(int, os.getenv("OWNER_ID", "").split())) # list seperated via space
DB_NAME = os.getenv("DB_NAME", "telegram_downloader")
STRING = os.getenv("STRING", None) # optional
LOG_GROUP = int(os.getenv("LOG_GROUP", "")) # optional with -100
FORCE_SUB = int(os.getenv("FORCE_SUB", "")) # optional with -100
MASTER_KEY = os.getenv("MASTER_KEY", "gK8HzLfT9QpViJcYeB5wRa3DmN7P2xUq") # for session encryption
IV_KEY = os.getenv("IV_KEY", "s7Yx5CpVmE3F") # for decryption
YT_COOKIES = os.getenv("YT_COOKIES", YTUB_COOKIES)
INSTA_COOKIES = os.getenv("INSTA_COOKIES", INST_COOKIES)
FREEMIUM_LIMIT = int(os.getenv("FREEMIUM_LIMIT", "10"))
PREMIUM_LIMIT = int(os.getenv("PREMIUM_LIMIT", "500000000"))
JOIN_LINK = os.getenv("JOIN_LINK", "https://t.me/skillwallahhaina") # this link for start command message
ADMIN_CONTACT = os.getenv("ADMIN_CONTACT", "https://t.me/skillwallah1")


